### ISSUE TITLE
Compatibility with redux-saga 1.0.0

### ISSUE THREAD

**Issue by tsirysndr** [ConsenSys-archive/drizzle-legacy#168]

**Comment by DiscRisknBisque** [comment]
Hi @realtsiry, are you experiencing any compatibility issues with `redux-saga` pre-1.0.0?

**Comment by DiscRisknBisque** [comment]
If you are experiencing any compatibility issues with redux-saga 1.0.0 or pre-1.0.0, please re-open.

**Comment by cds-amal** [comment]
@Ezerous, @realtsiry Sorry for the confusion. we're investigating to see if redux-saga's 1.0's breaking changes prevents us from upgrading

**Comment by barlock** [comment]
I've just experienced a really weird one. Using saga 1.x, none of my saga's are called.

```js
export function* initializeGame(action) {
  // On 1.0, this is never called
  console.log('initialize Game', action);
}

/**
 * A game redux saga, performs side effects
 */
export default function* gameSaga() {
  yield takeLatest('DRIZZLE_INITIALIZED', initializeGame);
}
```

When I downgrade to 0.16 it works as expected. 

I'm not 100% sure why this is, but I suspect this is because the `dist` packs it's own version of redux-saga so using 1.0 is a completely different saga instance.

**Comment by cds-amal** [comment]
Thanks for reporting this @barlock. [redux-sagas 1.0 introduced breaking changes](https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0) and we're investigating a migration path. Sorry for the inconvenience!
