### ISSUE TITLE
Creating the possibility to use a specific contract address

### ISSUE THREAD

**Issue by nieldlr** [ConsenSys-archive/drizzle-legacy#9]
Heya team,

love this! I coded up a very similar layer for my dapp services.

I'd love to give this a try, but my workflow works a bit differently than the usual truffle setup. I use Truffle to code & test, but sometimes deploy the contract by hand (not through truffle migrate) and also, I use contract factories to deploy copies of the contract for other users. Meaning, that I end up with addresses that's not listed in the truffle builds.

I was wondering, and I'm pretty sure this might come up in the future, is there a possibility that we can add a feature to specify the contract address when instantiating the drizzle contract?

Curious to hear your thoughts on this more and if this perhaps on the roadmap? I can help too if you're stuck with time/priorities.

**Comment by adklempner** [comment]
Oops, just now seeing this issue after opening mine.

@nieldlr do you want to share ideas of how we could implement this?

I'm wondering if implementing Drizzle as a regular Redux component instead of a provider might make more sense.

**Comment by nieldlr** [comment]
Heya @adklempner,

I haven't quite given it an exact thought yet. Just currently on a break this week. Will wrap back round early next week with some ideas 👍

**Comment by DiscRisknBisque** [comment]
@nieldlr Thank you and apologies for responding so late! :)

Would love to add this to v1.2. Since the contract instances use `web3.eth.Contract`, this could be implemented as something like `drizzle.addContract()`, accepting either an artifact file or an object with `web3.eth.Contract` params.

This could go for the initial options object as well, with drizzle running a check for whether the next element in options.contracts is an artifact or `web3.eth.Contract` params.

@adklempner Referenced the dynamic contract addition above also.

**Comment by LayneHaber** [comment]
Any idea when this type of functionality would become available?

**Comment by youfoundron** [comment]
Loving the motivation behind this lib, keep up the great work! 😄 

Wanted to add that forcing users to use an artifacts file rather than allowing them to specify contracts via a deployed address and JSON abi, is coupling this library with the rest of the truffle ecosystem in a way that for many is going to be a dealbreaker.

Lots people like to use truffle for local development on ganache, but would much rather deploy contracts to ropsten / mainnet manually than use the compile & migrate cli tools.

**Comment by gconaty** [comment]
Looking through the code a bit @DiscRiskandBisque would the recommended solution be to modify the redux state structure for contracts https://github.com/trufflesuite/drizzle/blob/master/src/drizzleStatus/drizzleStatusSaga.js#L36

to have a secondary dimension of `address`?  Perhaps also maintaining back-compat by having the 'default' still be `contracts.[contractName]`?

Fleshing it out in more detail would probably also require a `drizzle.removeContract(name,address)` or similar so as not to process blocks for contracts that are no longer of interest.

**Comment by nieldlr** [comment]
> Would love to add this to v1.2. Since the contract instances use web3.eth.Contract, this could be implemented as something like drizzle.addContract(), accepting either an artifact file or an object with web3.eth.Contract params.
> This could go for the initial options object as well, with drizzle running a check for whether the next element in options.contracts is an artifact or web3.eth.Contract params.

@DiscRiskandBisque sorry for dropping off here. Those sound great to me 👍Excited to see it live so I can try this out :)

**Comment by asselstine** [comment]
This would be fantastic!

@DiscRiskandBisque is there anyone working on this actively?  I could submit a PR

**Comment by asselstine** [comment]
I couldn't wait; I added the code for using Web3 Contract instances directly:

See PR https://github.com/trufflesuite/drizzle/pull/65

**Comment by soundyogi** [comment]
this issue could be closed then no?

**Comment by soundyogi** [comment]
This Issue is resolved and can be closed.

**Comment by DiscRisknBisque** [comment]
Thank you for your hard work @asselstine !
